/*Creating your database*/

/*CREATEDB PubSchema*/

/*To open the postgres shell at the created database*/
/*psql PubSchema*/


/*
DROP TABLE AUTHOR;
DROP TABLE PUBLICATION;
DROP TABLE PUBLISHES;
DROP TABLE BOOK;
DROP TABLE INCOLLECTION;
DROP TABLE INPROCEEDINGS;
DROP TABLE ARTICLES;
*/


DROP TABLE IF EXISTS AUTHOR ,PUBLICATION ,PUBLISHES ,BOOK ,INCOLLECTION ,INPROCEEDINGS ,ARTICLES CASCADE;

/*TABLE AUTHOR*/
create table AUTHOR (ID INT PRIMARY KEY NOT NULL, NAME TEXT, HOMEPAGE TEXT);


/*TABLE PUBLICATION*/
create table PUBLICATION (
PUBID INT PRIMARY KEY NOT NULL,
PUBKEY TEXT UNIQUE NOT NULL,
TITLE TEXT,
YEAR TEXT
);

/*TABLE PUBLISHES*/
CREATE TABLE PUBLISHES (
ID INT NOT NULL,
PUBID INT NOT NULL,
PRIMARY KEY(ID,PUBID),
FOREIGN KEY(ID) REFERENCES AUTHOR,
FOREIGN KEY(PUBID) REFERENCES PUBLICATION
);

/*TABLE ARTICLES*/
create table ARTICLE (
PUB_ID INT UNIQUE NOT NULL,
ARTICLE_NUMBER TEXT ,
VOLUME TEXT,
JOURNAL TEXT ,
MONTH TEXT,
FOREIGN KEY (PUB_ID) REFERENCES PUBLICATION (PUBID)
);

/*TABLE BOOK*/
create table BOOK (
PUB_ID INT NOT NULL, 
ISBN TEXT,
PUBLISHER TEXT,
FOREIGN KEY (PUB_ID) REFERENCES PUBLICATION (PUBID)
);

/*TABLE INCOLLECTION*/
create table INCOLLECTION (
PUB_ID INT UNIQUE NOT NULL, 
ISBN TEXT,
PUBLISHER TEXT,
BOOKTITLE TEXT,
FOREIGN KEY (PUB_ID) REFERENCES PUBLICATION (PUBID)
);

/*TABLE INPROCEEDINGS*/
create table INPROCEEDINGS (
PUB_ID INT UNIQUE NOT NULL, 
EDITOR TEXT,
BOOKTITLE TEXT,
FOREIGN KEY (PUB_ID) REFERENCES PUBLICATION (PUBID)
);


